### ISSUE TITLE
Pulsed Field Magnets will still rip items from your inventory when the option to disable that is on

### ISSUE THREAD

**Issue by AsheIsAmazing** [egocarib/CavesOfQud-QudUX-v2#9]
As per title. Regardless of if the setting is on or off you are still susceptible to the pull of Pulsed Field Magnets.

**Comment by egocarib** [comment]
Fixed in 15429333f2a5dacdeee0e2286275dabdc2274cd2. I will wait until the current beta moves to stable branch before I push this fix to Steam, but if you are playing the beta branch and want to get this fix now, you can manually install the latest release: https://github.com/egocarib/CavesOfQud-QudUX-v2/releases/tag/2021.09.03
